### ISSUE TITLE
[FR] Support arm64

### ISSUE THREAD

**Issue by huyz** [webarch-coop/ansible-role-kitty#3]
I figure all that's needed is to have a map:

```yaml
    kitty_arch_map: {
        "x86_64": "x86_64",
        "aarch64": "arm64",
        "aarch64_be": "arm64",
        "armv8b": "arm64",
        "armv8l": "arm64",
        "i386": "i686",
        "i686": "i686",
    }
```

And then just replace all mentions of `x86_64` in the code with `{{ kitty_arch_map[ansible_architecture] | d('INVALID') }}`
